export const ircaMonths = ["Enero","2022"];

export const ircaLegend = [
  {
    range: "80.1 - 100",
    risk: "INVIABLE SANITARIAMENTE",
    notification:
      "Informar a la persona prestadora, al COVE, Alcalde, Gobernador, SSPD, MPS, INS, MAVDT, Contraloría General y Procuraduría General.",
    action:
      "Agua no apta para consumo humano, gestión directa de acuerdo a su competencia de la persona prestadora, alcaldes, gobernadores y entidades del orden nacional.",
    color: "#dc2626",
  },
  {
    range: "35.1 - 80",
    risk: "ALTO",
    notification:
      "Informar a la persona prestadora, COVE, Alcalde, Gobernador y a la SSPD.",
    action:
      "Agua no apta para consumo humano, gestión directa de acuerdo a su competencia de la persona prestadora y de los alcaldes y gobernadores respectivos.",
    color: "#f97316",
  },
  {
    range: "14.1 - 35",
    risk: "MEDIO",
    notification:
      "Informar a la persona prestadora, COVE, Alcalde y Gobernador.",
    action:
      "Agua no apta para consumo humano, gestión directa de la persona prestadora.",
    color: "#eab308",
  },
  {
    range: "5.1 - 14",
    risk: "BAJO",
    notification:
      "Informar a la persona prestadora y al COVE.",
    action:
      "Agua no apta para consumo humano, susceptible de mejoramiento.",
    color: "#22c55e",
  },
  {
    range: "0 - 5",
    risk: "SIN RIESGO",
    notification: "Continuar el control y la vigilancia.",
    action: "Agua apta para consumo humano. Continuar la vigilancia.",
    color: "#16a34a",
  },
];

export const hydroSites = [
  {
    id: "pozo-un-ene",
    name: "Pozo UN - Ene",
    lat: -4.19194444444444,
    lng: -69.9397222222222,
    month: "Enero",
    irca: 3.614457831325301,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: 10,
      conductividadEspecifica: 39.4,
      alcalinidadTotal: 18,
      acidezTotal: 6,
      durezaTotal: 10,
      durezaCalcica: 2.5,
      durezaMagnesica: 8,
      calcioPorTitulacion: 1,
      carbonoOrganicoTotal: 0.5,
      fluoruros: 0.03,
      nitritos: 0.05,
      nitratos: 0.8,
      cloruros: 0.2,
      sulfatos: 0.2,
      ortofosfatos: 0.3,
      solidosTotales: 53,
      solidosSuspendidosTotales: 2.5,
      coliformesTotales: null,
      eColi: null,
      turbiedad: 1.74,
      pH: 6.15,
      magnesio: 2,
      hierro: 0.05,
      manganeso: 0.025,
      zinc: 0.025,
    },
  },
  {
    id: "rio-amazonas-ene",
    name: "Rio Amazonas - Ene",
    lat: -4.27019,
    lng: -69.948582,
    month: "Enero",
    irca: 69.3641975308642,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: 100,
      conductividadEspecifica: 168.9,
      alcalinidadTotal: 73,
      acidezTotal: 2.5,
      durezaTotal: 80,
      durezaCalcica: 60,
      durezaMagnesica: 20,
      calcioPorTitulacion: 24,
      carbonoOrganicoTotal: 4.16,
      fluoruros: 0.1,
      nitritos: 0.05,
      nitratos: 1.6,
      cloruros: 5.3,
      sulfatos: 13,
      ortofosfatos: 0.3,
      solidosTotales: 754,
      solidosSuspendidosTotales: 605,
      coliformesTotales: 1700,
      eColi: 1100,
      turbiedad: 512,
      pH: 7.84,
      magnesio: 5,
      hierro: 4.6,
      manganeso: 0.35,
      zinc: 0.025,
    },
  },
  {
    id: "numae-ene",
    name: "NUMAE - Ene",
    lat: -4.21752946406046,
    lng: -69.9403772026435,
    month: "Enero",
    irca: 50.364197530864196,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: 9,
      conductividadEspecifica: 69,
      alcalinidadTotal: 6,
      acidezTotal: 16,
      durezaTotal: 7,
      durezaCalcica: 2.5,
      durezaMagnesica: 7,
      calcioPorTitulacion: 0,
      carbonoOrganicoTotal: 0.5,
      fluoruros: 0.01,
      nitritos: 0.05,
      nitratos: 19.2,
      cloruros: 15,
      sulfatos: 0.5,
      ortofosfatos: 0.1,
      solidosTotales: 54,
      solidosSuspendidosTotales: 2.5,
      coliformesTotales: 9,
      eColi: 9,
      turbiedad: 0.96,
      pH: 5.35,
      magnesio: 2,
      hierro: 0.05,
      manganeso: 0.05,
      zinc: 0.025,
    },
  },
  {
    id: "pz-nm-016",
    name: "PZ-NM-016",
    lat: -4.1915,
    lng: -69.9468,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 5.48,
      acidezTotal: null,
      durezaTotal: 1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.832,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.6,
      sulfatos: 0.1,
      ortofosfatos: 32,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.4,
      magnesio: 0.036,
      hierro: 0.203,
      manganeso: 0.036,
      zinc: null,
    },
  },
  {
    id: "pz-nm-015",
    name: "PZ-NM-015",
    lat: -4.1907,
    lng: -69.9471,
    month: "2022",
    irca: 17.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 7.09,
      acidezTotal: null,
      durezaTotal: 1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.795,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.45,
      sulfatos: 0.1,
      ortofosfatos: 27,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 30.9,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.5,
      magnesio: 0.004,
      hierro: 0.045,
      manganeso: 0.004,
      zinc: null,
    },
  },
  {
    id: "pz-nm-005",
    name: "PZ-NM-005",
    lat: -4.1981,
    lng: -69.9464,
    month: "2022",
    irca: 19,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 10.75,
      acidezTotal: null,
      durezaTotal: 5.24,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 2.84,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.33,
      sulfatos: 0.24,
      ortofosfatos: 40,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 5,
      pH: 4.9,
      magnesio: 0.057,
      hierro: 1.333,
      manganeso: 0.057,
      zinc: null,
    },
  },
  {
    id: "pz-nm-007",
    name: "PZ-NM-007",
    lat: -4.2103,
    lng: -69.9433,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 16.23,
      acidezTotal: null,
      durezaTotal: 2.82,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.738,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.4,
      sulfatos: 0.38,
      ortofosfatos: 59,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.4,
      magnesio: 0.019,
      hierro: 0.045,
      manganeso: 0.019,
      zinc: null,
    },
  },
  {
    id: "pz-nm-008",
    name: "Pz-NM-008",
    lat: -4.2175,
    lng: -69.9425,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 8.38,
      acidezTotal: null,
      durezaTotal: 2.14,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.962,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.27,
      sulfatos: 0.75,
      ortofosfatos: 48,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.2,
      magnesio: 0.039,
      hierro: 0.045,
      manganeso: 0.039,
      zinc: null,
    },
  },
  {
    id: "pz-nm-047",
    name: "PZ-NM-047",
    lat: -4.0772,
    lng: -70.0034,
    month: "2022",
    irca: 69.24657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 6.66,
      acidezTotal: null,
      durezaTotal: 3.5,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.677,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.1,
      sulfatos: 0.5,
      ortofosfatos: 27,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 41,
      eColi: 10,
      turbiedad: 14,
      pH: 5.5,
      magnesio: 0.777,
      hierro: 1.639,
      manganeso: 0.777,
      zinc: null,
    },
  },
  {
    id: "pz-nm-05",
    name: "PZ-NM-05",
    lat: -4.1981,
    lng: -69.9464,
    month: "2022",
    irca: 18.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.214,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.24,
      cloruros: 0.1,
      sulfatos: 1.16,
      ortofosfatos: 6,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 4.1,
      eColi: 0,
      turbiedad: 1,
      pH: 6.4,
      magnesio: 6,
      hierro: 0.045,
      manganeso: 6,
      zinc: null,
    },
  },
  {
    id: "pz-nm-001",
    name: "PZ-NM-001",
    lat: -4.0906,
    lng: -69.9867,
    month: "2022",
    irca: 69.24657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 16.77,
      acidezTotal: null,
      durezaTotal: 20.39,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 6.862,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.1,
      sulfatos: 1.06,
      ortofosfatos: 60,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 4352,
      eColi: 10,
      turbiedad: 160,
      pH: 5.1,
      magnesio: 0.227,
      hierro: 6.041,
      manganeso: 0.227,
      zinc: null,
    },
  },
  {
    id: "pz-nm-009",
    name: "PZ-NM-009",
    lat: -4.2195,
    lng: -69.9368,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 12.08,
      acidezTotal: null,
      durezaTotal: 3.5,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.032,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.89,
      cloruros: 0.1,
      sulfatos: 0.1,
      ortofosfatos: 40,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.1,
      magnesio: 0.023,
      hierro: 0.045,
      manganeso: 0.023,
      zinc: null,
    },
  },
  {
    id: "pz-nm-006",
    name: "PZ-NM-006",
    lat: -4.2147,
    lng: -69.9425,
    month: "2022",
    irca: 4,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 2.48,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.546,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.54,
      sulfatos: 0.1,
      ortofosfatos: 14,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.7,
      magnesio: 0.017,
      hierro: 0.411,
      manganeso: 0.017,
      zinc: null,
    },
  },
  {
    id: "pz-nm-03",
    name: "PZ-NM-03",
    lat: -4.1733,
    lng: -69.9554,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 6.47,
      acidezTotal: null,
      durezaTotal: 3.11,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.53,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.45,
      cloruros: 0.24,
      sulfatos: 0.1,
      ortofosfatos: 15,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.7,
      magnesio: 0.009,
      hierro: 0.045,
      manganeso: 0.009,
      zinc: null,
    },
  },
  {
    id: "pz-nm-030",
    name: "PZ-NM-030",
    lat: -4.1098,
    lng: -69.9631,
    month: "2022",
    irca: 17.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.247,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.68,
      cloruros: 0.4,
      sulfatos: 0.1,
      ortofosfatos: 8,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 6.3,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5,
      magnesio: 0.0015,
      hierro: 0.045,
      manganeso: 0.0015,
      zinc: null,
    },
  },
  {
    id: "pz-nm-048",
    name: "PZ-NM-048",
    lat: -4.0795,
    lng: -70.0059,
    month: "2022",
    irca: 50.24657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 5.18,
      acidezTotal: null,
      durezaTotal: 3.12,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.804,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.33,
      cloruros: 0.22,
      sulfatos: 0.1,
      ortofosfatos: 16,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 56.8,
      eColi: 4.1,
      turbiedad: 0.5,
      pH: 6.5,
      magnesio: 0.018,
      hierro: 0.161,
      manganeso: 0.018,
      zinc: null,
    },
  },
  {
    id: "pz-nm-022",
    name: "PZ-NM-022",
    lat: -4.1069,
    lng: -69.9697,
    month: "2022",
    irca: 53.24657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 26.96,
      acidezTotal: null,
      durezaTotal: 17.09,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 5.316,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.39,
      cloruros: 1.82,
      sulfatos: 0.1,
      ortofosfatos: 60,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 8330,
      eColi: 1,
      turbiedad: 0.5,
      pH: 4.6,
      magnesio: 0.098,
      hierro: 3.339,
      manganeso: 0.098,
      zinc: null,
    },
  },
  {
    id: "pz-nm-051",
    name: "PZ-NM-051",
    lat: -4.2261,
    lng: -69.9351,
    month: "2022",
    irca: 18.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.158,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 10.82,
      sulfatos: 0.1,
      ortofosfatos: 50,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 1,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.3,
      magnesio: 0.103,
      hierro: 0.045,
      manganeso: 0.103,
      zinc: null,
    },
  },
  {
    id: "pz-nm-036",
    name: "PZ-NM-036",
    lat: -4.2232,
    lng: -69.9382,
    month: "2022",
    irca: 66.74657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.477,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 3.57,
      sulfatos: 0.1,
      ortofosfatos: 56,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 171,
      eColi: 10,
      turbiedad: 3.7,
      pH: 4.8,
      magnesio: 0.017,
      hierro: 0.045,
      manganeso: 0.017,
      zinc: null,
    },
  },
  {
    id: "pz-nm-033",
    name: "PZ-NM-033",
    lat: -4.2238,
    lng: -69.9387,
    month: "2022",
    irca: 66.74657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 6.26,
      acidezTotal: null,
      durezaTotal: 10.68,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.677,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 16.99,
      sulfatos: 0.1,
      ortofosfatos: 90,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 1236,
      eColi: 146,
      turbiedad: 12,
      pH: 4.8,
      magnesio: 0.036,
      hierro: 0.045,
      manganeso: 0.036,
      zinc: null,
    },
  },
  {
    id: "pz-nm-056",
    name: "PZ-NM-056",
    lat: -4.2256,
    lng: -69.9348,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.341,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 2.92,
      sulfatos: 0.1,
      ortofosfatos: 47,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.3,
      magnesio: 0.058,
      hierro: 0.045,
      manganeso: 0.058,
      zinc: null,
    },
  },
  {
    id: "pz-nm-055",
    name: "PZ-NM-055",
    lat: -4.2256,
    lng: -69.935,
    month: "2022",
    irca: 18.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.265,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 3.23,
      sulfatos: 0.1,
      ortofosfatos: 48,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 13.4,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.6,
      magnesio: 0.126,
      hierro: 0.045,
      manganeso: 0.126,
      zinc: null,
    },
  },
  {
    id: "pz-nm-034",
    name: "PZ-NM-034",
    lat: -4.223,
    lng: -69.9389,
    month: "2022",
    irca: 66.74657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 2.52,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.634,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 8.33,
      sulfatos: 0.1,
      ortofosfatos: 69,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 160,
      eColi: 41,
      turbiedad: 16,
      pH: 4.8,
      magnesio: 0.029,
      hierro: 0.045,
      manganeso: 0.029,
      zinc: null,
    },
  },
  {
    id: "pz-nm-027",
    name: "PZ-NM-027",
    lat: -4.1918,
    lng: -69.9301,
    month: "2022",
    irca: 17.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 63.58,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.492,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.1,
      sulfatos: 0.1,
      ortofosfatos: 11,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 2,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.5,
      magnesio: 0.028,
      hierro: 0.09,
      manganeso: 0.028,
      zinc: null,
    },
  },
  {
    id: "pz-nm-026",
    name: "PZ-NM-026",
    lat: -4.2166,
    lng: -69.9342,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 5.39,
      acidezTotal: null,
      durezaTotal: 80.92,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.205,
      carbonoOrganicoTotal: 2.67,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 3.91,
      sulfatos: 0.1,
      ortofosfatos: 45,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 1.6,
      pH: 4.8,
      magnesio: 0.011,
      hierro: 0.097,
      manganeso: 0.011,
      zinc: null,
    },
  },
  {
    id: "pz-nm-025",
    name: "PZ-NM-025",
    lat: -4.2121,
    lng: -69.9405,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 42.77,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.645,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 3.78,
      sulfatos: 0.1,
      ortofosfatos: 50,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 1,
      pH: 4.9,
      magnesio: 0.053,
      hierro: 0.045,
      manganeso: 0.053,
      zinc: null,
    },
  },
  {
    id: "pz-nm-007",
    name: "PZ-NM-007",
    lat: -4.2103,
    lng: -69.9433,
    month: "2022",
    irca: 32.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 79,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.562,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.55,
      sulfatos: 0.1,
      ortofosfatos: 20,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 41060,
      eColi: 0,
      turbiedad: 28,
      pH: 5.3,
      magnesio: 0.013,
      hierro: 0.045,
      manganeso: 0.013,
      zinc: null,
    },
  },
  {
    id: "pz-nm-012",
    name: "PZ-NM-012",
    lat: -4.2135,
    lng: -69.9425,
    month: "2022",
    irca: 66.74657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 5.88,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.979,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 2.14,
      sulfatos: 1.38,
      ortofosfatos: 22,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 166.4,
      eColi: 75,
      turbiedad: 105,
      pH: 5,
      magnesio: 0.009,
      hierro: 0.045,
      manganeso: 0.009,
      zinc: null,
    },
  },
  {
    id: "pz-nm-024",
    name: "PZ-NM-024",
    lat: -4.1907,
    lng: -69.9497,
    month: "2022",
    irca: 51.74657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.461,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 1.32,
      sulfatos: 0.55,
      ortofosfatos: 32,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 24.1,
      eColi: 15.8,
      turbiedad: 0.5,
      pH: 4.5,
      magnesio: 0.005,
      hierro: 0.045,
      manganeso: 0.005,
      zinc: null,
    },
  },
  {
    id: "pz-nm-031",
    name: "PZ-NM-031",
    lat: -4.12,
    lng: -69.9475,
    month: "2022",
    irca: 17.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.749,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.55,
      sulfatos: 0.33,
      ortofosfatos: 10,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 8,
      pH: 5.2,
      magnesio: 0.006,
      hierro: 0.045,
      manganeso: 0.006,
      zinc: null,
    },
  },
  {
    id: "pz-nm-032",
    name: "PZ-NM-032",
    lat: -4.1187,
    lng: -69.9455,
    month: "2022",
    irca: 66.74657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 2.6,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.01,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 1.82,
      sulfatos: 0.1,
      ortofosfatos: 17,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 884,
      eColi: 63,
      turbiedad: 5,
      pH: 4.4,
      magnesio: 0.0015,
      hierro: 0.045,
      manganeso: 0.0015,
      zinc: null,
    },
  },
  {
    id: "pz-nm-028",
    name: "PZ-NM-028",
    lat: -4.2041,
    lng: -69.9404,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.605,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 4.34,
      sulfatos: 0.1,
      ortofosfatos: 66,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.1,
      magnesio: 0.012,
      hierro: 0.045,
      manganeso: 0.012,
      zinc: null,
    },
  },
  {
    id: "pz-nm-006",
    name: "PZ-NM-006",
    lat: -4.2147,
    lng: -69.9425,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 13.98,
      acidezTotal: null,
      durezaTotal: 10.02,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 2.686,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 7.84,
      sulfatos: 0.1,
      ortofosfatos: 60,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.9,
      magnesio: 0.007,
      hierro: 0.045,
      manganeso: 0.007,
      zinc: null,
    },
  },
  {
    id: "pz-dm-01",
    name: "PZ-DM-01",
    lat: -4.2111,
    lng: -69.9353,
    month: "2022",
    irca: 34,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 23.13,
      acidezTotal: null,
      durezaTotal: 15.41,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 4.653,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.38,
      sulfatos: 1.09,
      ortofosfatos: 43,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 111.2,
      eColi: 0,
      turbiedad: 18,
      pH: 5.3,
      magnesio: 0.027,
      hierro: 2.006,
      manganeso: 0.027,
      zinc: null,
    },
  },
  {
    id: "pz-nm-058",
    name: "PZ-NM-058",
    lat: -4.2311,
    lng: -69.9286,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 7.88,
      acidezTotal: null,
      durezaTotal: 3.08,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.772,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 2.93,
      sulfatos: 0.79,
      ortofosfatos: 20,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.5,
      magnesio: 0.04,
      hierro: 0.045,
      manganeso: 0.04,
      zinc: null,
    },
  },
  {
    id: "pz-nm-059",
    name: "PZ-NM-059",
    lat: -4.2319,
    lng: -69.9344,
    month: "2022",
    irca: 3.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 21.19,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 4.607,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 32.62,
      sulfatos: 5.46,
      ortofosfatos: 153,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.1,
      magnesio: 0.437,
      hierro: 0.119,
      manganeso: 0.437,
      zinc: null,
    },
  },
  {
    id: "pz-nm-057",
    name: "PZ-NM-057",
    lat: -4.2289,
    lng: -69.9181,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 12.83,
      acidezTotal: null,
      durezaTotal: 5.97,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.166,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 2.36,
      sulfatos: 0.76,
      ortofosfatos: 40,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.5,
      magnesio: 0.013,
      hierro: 0.045,
      manganeso: 0.013,
      zinc: null,
    },
  },
  {
    id: "pz-nm-060",
    name: "PZ-NM-060",
    lat: -4.2286,
    lng: -69.9383,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 4.82,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.521,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 1.9,
      sulfatos: 3.35,
      ortofosfatos: 15,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.8,
      magnesio: 0.049,
      hierro: 0.045,
      manganeso: 0.049,
      zinc: null,
    },
  },
  {
    id: "pz-nm-023",
    name: "PZ-NM-023",
    lat: -4.1067,
    lng: -69.9706,
    month: "2022",
    irca: 66.74657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 7.95,
      acidezTotal: null,
      durezaTotal: 5.66,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.999,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.1,
      sulfatos: 0.1,
      ortofosfatos: 26,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 9208,
      eColi: 41,
      turbiedad: 3.8,
      pH: 5.1,
      magnesio: 0.039,
      hierro: 0.168,
      manganeso: 0.039,
      zinc: null,
    },
  },
  {
    id: "pz-nm-021",
    name: "PZ-NM-021",
    lat: -4.076,
    lng: -70.0019,
    month: "2022",
    irca: 34,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 21.68,
      acidezTotal: null,
      durezaTotal: 13.94,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 3.798,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.1,
      sulfatos: 0.1,
      ortofosfatos: 32,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 3.1,
      eColi: 0,
      turbiedad: 26,
      pH: 6.3,
      magnesio: 0.093,
      hierro: 5.365,
      manganeso: 0.093,
      zinc: null,
    },
  },
  {
    id: "pz-nm-02",
    name: "PZ-NM-02",
    lat: -4.1761,
    lng: -69.9531,
    month: "2022",
    irca: 17.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 6.92,
      acidezTotal: null,
      durezaTotal: 5.23,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.546,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 1.19,
      sulfatos: 0.1,
      ortofosfatos: 25,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 1,
      eColi: 0,
      turbiedad: 1.1,
      pH: 5.7,
      magnesio: 0.016,
      hierro: 0.045,
      manganeso: 0.016,
      zinc: null,
    },
  },
  {
    id: "pz-nm-003",
    name: "PZ-NM-003",
    lat: -4.1733,
    lng: -69.9554,
    month: "2022",
    irca: 19,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 16,
      acidezTotal: null,
      durezaTotal: 12.64,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 2.812,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 2.77,
      sulfatos: 0.1,
      ortofosfatos: 52,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 7.8,
      pH: 5,
      magnesio: 0.061,
      hierro: 3.293,
      manganeso: 0.061,
      zinc: null,
    },
  },
  {
    id: "pz-nm-037",
    name: "PZ-NM-037",
    lat: -4.2404,
    lng: -69.9408,
    month: "2022",
    irca: 17.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 12.18,
      acidezTotal: null,
      durezaTotal: 14.81,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 3.419,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 3.12,
      sulfatos: 0.1,
      ortofosfatos: 96,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 3,
      pH: 5.3,
      magnesio: 0.055,
      hierro: 0.045,
      manganeso: 0.055,
      zinc: null,
    },
  },
  {
    id: "pz-nm-045",
    name: "PZ-NM-045",
    lat: -4.2235,
    lng: -69.9392,
    month: "2022",
    irca: 17.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 10.32,
      acidezTotal: null,
      durezaTotal: 14.38,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 2.463,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.1,
      sulfatos: 0.1,
      ortofosfatos: 62,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 41,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.2,
      magnesio: 0.03,
      hierro: 0.045,
      manganeso: 0.03,
      zinc: null,
    },
  },
  {
    id: "pz-nm-014",
    name: "PZ-NM-014",
    lat: -4.2175,
    lng: -69.9403,
    month: "2022",
    irca: 33.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 5.23,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.553,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 3.93,
      sulfatos: 2.04,
      ortofosfatos: 72,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 1,
      eColi: 0,
      turbiedad: 5.9,
      pH: 5.4,
      magnesio: 0.139,
      hierro: 0.045,
      manganeso: 0.139,
      zinc: null,
    },
  },
  {
    id: "pz-nm-029",
    name: "PZ-NM-029",
    lat: -4.2128,
    lng: -69.9403,
    month: "2022",
    irca: 53.24657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 20.13,
      acidezTotal: null,
      durezaTotal: 10.46,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.729,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.1,
      sulfatos: 3.34,
      ortofosfatos: 65,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 2603,
      eColi: 29.2,
      turbiedad: 1.1,
      pH: 6.3,
      magnesio: 0.064,
      hierro: 1.099,
      manganeso: 0.064,
      zinc: null,
    },
  },
  {
    id: "pz-nm-02",
    name: "PZ-NM-02",
    lat: -4.1761,
    lng: -69.9531,
    month: "2022",
    irca: 32.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 14.66,
      acidezTotal: null,
      durezaTotal: 16.99,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 5.884,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 3.44,
      sulfatos: 6.55,
      ortofosfatos: 86,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 1,
      eColi: 0,
      turbiedad: 14,
      pH: 4.3,
      magnesio: 0.029,
      hierro: 0.045,
      manganeso: 0.029,
      zinc: null,
    },
  },
  {
    id: "pz-nm-042",
    name: "PZ-NM-042",
    lat: -4.2267,
    lng: -69.9422,
    month: "2022",
    irca: 21.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 12.64,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.343,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 26.33,
      cloruros: 19.59,
      sulfatos: 0.1,
      ortofosfatos: 92,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 1,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.6,
      magnesio: 0.129,
      hierro: 0.192,
      manganeso: 0.129,
      zinc: null,
    },
  },
  {
    id: "pz-nm-050",
    name: "PZ-NM-050",
    lat: -4.2281,
    lng: -69.9197,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 9.19,
      acidezTotal: null,
      durezaTotal: 2.48,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.457,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 3.87,
      cloruros: 4.41,
      sulfatos: 0.99,
      ortofosfatos: 35,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.8,
      magnesio: 0.009,
      hierro: 0.185,
      manganeso: 0.009,
      zinc: null,
    },
  },
  {
    id: "pz-nm-044",
    name: "PZ-NM-044",
    lat: -4.2261,
    lng: -69.9419,
    month: "2022",
    irca: 5.5,
    risk: "Bajo",
    color: "#84cc16",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 10.22,
      acidezTotal: null,
      durezaTotal: 10.89,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.645,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 12.69,
      cloruros: 23.44,
      sulfatos: 0.1,
      ortofosfatos: 93,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.1,
      magnesio: 0.093,
      hierro: 0.266,
      manganeso: 0.093,
      zinc: null,
    },
  },
  {
    id: "pz-nm-052",
    name: "PZ-NM-052",
    lat: -4.2221,
    lng: -69.9374,
    month: "2022",
    irca: 20.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 8.28,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.677,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 11.81,
      cloruros: 16.39,
      sulfatos: 1.39,
      ortofosfatos: 52,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 28,
      pH: 5.1,
      magnesio: 0.057,
      hierro: 0.16,
      manganeso: 0.057,
      zinc: null,
    },
  },
  {
    id: "pz-nm-013",
    name: "PZ-NM-013",
    lat: -4.0997,
    lng: -69.9389,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 2.18,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.596,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.42,
      cloruros: 0.22,
      sulfatos: 0.1,
      ortofosfatos: 10,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.6,
      magnesio: 0.01,
      hierro: 0.226,
      manganeso: 0.01,
      zinc: null,
    },
  },
  {
    id: "pz-nm-049",
    name: "PZ-NM-049",
    lat: -4.2283,
    lng: -69.9198,
    month: "2022",
    irca: 54.24657534246575,
    risk: "Alto",
    color: "#dc2626",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 41.91,
      acidezTotal: null,
      durezaTotal: 25.71,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 6.414,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 0.73,
      sulfatos: 0.1,
      ortofosfatos: 41,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 19863,
      eColi: 62,
      turbiedad: 0.5,
      pH: 5.2,
      magnesio: 0.1512,
      hierro: 5.454,
      manganeso: 0.1512,
      zinc: null,
    },
  },
  {
    id: "pz-nm-038",
    name: "PZ-NM-038",
    lat: -4.2405,
    lng: -69.941,
    month: "2022",
    irca: 20.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 8.88,
      acidezTotal: null,
      durezaTotal: 4.79,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.615,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 10.94,
      cloruros: 13.49,
      sulfatos: 0.1,
      ortofosfatos: 48,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 9.7,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.5,
      magnesio: 0.037,
      hierro: 0.231,
      manganeso: 0.037,
      zinc: null,
    },
  },
  {
    id: "pz-nm-020",
    name: "PZ-NM-020",
    lat: -4.2381,
    lng: -69.9367,
    month: "2022",
    irca: 2.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 5.47,
      acidezTotal: null,
      durezaTotal: 8.28,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.216,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 5.97,
      sulfatos: 0.95,
      ortofosfatos: 46,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.5,
      magnesio: 0.0015,
      hierro: 0.106,
      manganeso: 0.0015,
      zinc: null,
    },
  },
  {
    id: "pz-nm-039",
    name: "PZ-NM-039",
    lat: -4.2225,
    lng: -69.9385,
    month: "2022",
    irca: 32.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 5.88,
      acidezTotal: null,
      durezaTotal: 6.1,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.355,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 21.99,
      sulfatos: 2.12,
      ortofosfatos: 96,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 57300,
      eColi: 0,
      turbiedad: 21,
      pH: 4.5,
      magnesio: 0.0015,
      hierro: 0.045,
      manganeso: 0.0015,
      zinc: null,
    },
  },
  {
    id: "pz-nm-053",
    name: "PZ-NM-053",
    lat: -4.2261,
    lng: -69.9319,
    month: "2022",
    irca: 3.5,
    risk: "Sin Riesgo",
    color: "#16a34a",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 5.26,
      acidezTotal: null,
      durezaTotal: 20.92,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 1.991,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.025,
      cloruros: 15.98,
      sulfatos: 0.82,
      ortofosfatos: 88,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 4.8,
      magnesio: 0.125,
      hierro: 0.045,
      manganeso: 0.125,
      zinc: null,
    },
  },
  {
    id: "pz-nm-054",
    name: "PZ-NM-054",
    lat: -4.2261,
    lng: -69.9322,
    month: "2022",
    irca: 6.5,
    risk: "Bajo",
    color: "#84cc16",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 7.33,
      acidezTotal: null,
      durezaTotal: 12.64,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 0.995,
      carbonoOrganicoTotal: 10.4,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.29,
      cloruros: 15.99,
      sulfatos: 0.84,
      ortofosfatos: 111,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 0,
      eColi: 0,
      turbiedad: 0.5,
      pH: 5.9,
      magnesio: 0.108,
      hierro: 0.045,
      manganeso: 0.108,
      zinc: null,
    },
  },
  {
    id: "pz-nm-061",
    name: "PZ-NM-061",
    lat: -4.2338,
    lng: -69.9306,
    month: "2022",
    irca: 32.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 53.88,
      acidezTotal: null,
      durezaTotal: 52.72,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 12.03,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 0.82,
      cloruros: 10.07,
      sulfatos: 4.79,
      ortofosfatos: 106,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 122.3,
      eColi: 0,
      turbiedad: 5.3,
      pH: 4.3,
      magnesio: 0.089,
      hierro: 0.17,
      manganeso: 0.089,
      zinc: null,
    },
  },
  {
    id: "pz-nm-040",
    name: "PZ-NM-040",
    lat: -4.2211,
    lng: -69.935,
    month: "2022",
    irca: 20.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 2.5,
      acidezTotal: null,
      durezaTotal: 10.89,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 3.048,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 27.54,
      cloruros: 30.74,
      sulfatos: 3.48,
      ortofosfatos: 109,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 5.2,
      eColi: 0,
      turbiedad: 1.4,
      pH: 4.6,
      magnesio: 0.065,
      hierro: 0.104,
      manganeso: 0.065,
      zinc: null,
    },
  },
  {
    id: "pz-nm-062",
    name: "PZ-NM-062",
    lat: -4.2222,
    lng: -69.9383,
    month: "2022",
    irca: 17.5,
    risk: "Medio",
    color: "#eab308",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: 6.4,
      acidezTotal: null,
      durezaTotal: 10.02,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: 2.488,
      carbonoOrganicoTotal: 1,
      fluoruros: null,
      nitritos: 0.025,
      nitratos: 7.03,
      cloruros: 20.57,
      sulfatos: 9.73,
      ortofosfatos: 165,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: 1,
      eColi: 0,
      turbiedad: 0.5,
      pH: null,
      magnesio: 0.0015,
      hierro: 0.184,
      manganeso: 0.0015,
      zinc: null,
    },
  },
  {
    id: "none",
    name: "None",
    lat: null,
    lng: null,
    month: "None",
    irca: null,
    risk: "None",
    color: "#6b7280",
    note: "",
    parameters: {
      colorAparente: null,
      conductividadEspecifica: null,
      alcalinidadTotal: null,
      acidezTotal: null,
      durezaTotal: null,
      durezaCalcica: null,
      durezaMagnesica: null,
      calcioPorTitulacion: null,
      carbonoOrganicoTotal: null,
      fluoruros: null,
      nitritos: null,
      nitratos: null,
      cloruros: null,
      sulfatos: null,
      ortofosfatos: null,
      solidosTotales: null,
      solidosSuspendidosTotales: null,
      coliformesTotales: null,
      eColi: null,
      turbiedad: null,
      pH: null,
      magnesio: null,
      hierro: null,
      manganeso: null,
      zinc: null,
    },
  },
];

export const parameterOrder = [
  { key: "turbiedad", label: "Turbiedad", unit: "UNT" },
  { key: "colorAparente", label: "Color aparente", unit: "UPC" },
  { key: "pH", label: "pH", unit: "Unidades" },
  { key: "conductividadEspecifica", label: "Conductividad específica", unit: "µS/cm 25°C" },
  { key: "alcalinidadTotal", label: "Alcalinidad total", unit: "mg/L CaCO₃" },
  { key: "acidezTotal", label: "Acidez total", unit: "mg/L CaCO₃" },
  { key: "durezaTotal", label: "Dureza total", unit: "mg/L CaCO₃" },
  { key: "durezaCalcica", label: "Dureza cálcica", unit: "mg/L CaCO₃" },
  { key: "durezaMagnesica", label: "Dureza magnésica", unit: "mg/L CaCO₃" },
  { key: "calcioPorTitulacion", label: "Calcio por titulación", unit: "mg/L Ca" },
  { key: "magnesio", label: "Magnesio", unit: "mg/L Mg" },
  { key: "hierro", label: "Hierro", unit: "mg/L Fe³⁺" },
  { key: "manganeso", label: "Manganeso", unit: "mg/L Mn⁷⁺" },
  { key: "carbonoOrganicoTotal", label: "Carbono orgánico total", unit: "mg/L C" },
  { key: "zinc", label: "Zinc", unit: "mg/L Zn" },
  { key: "fluoruros", label: "Fluoruros", unit: "mg/L F-" },
  { key: "nitritos", label: "Nitritos", unit: "mg/L N-NO₂-" },
  { key: "nitratos", label: "Nitratos", unit: "mg/L N-NO₃-" },
  { key: "cloruros", label: "Cloruros", unit: "mg/L Cl-" },
  { key: "sulfatos", label: "Sulfatos", unit: "mg/L SO₄²-" },
  { key: "ortofosfatos", label: "Ortofosfatos", unit: "mg/L PO₄³-" },
  { key: "solidosTotales", label: "Sólidos totales", unit: "mg/L" },
  { key: "solidosSuspendidosTotales", label: "Sólidos suspendidos totales", unit: "mg/L" },
  { key: "coliformesTotales", label: "Coliformes totales", unit: "NMP/100 mL" },
  { key: "eColi", label: "E. coli", unit: "NMP/100 mL" },
  { key: "sodio", label: "Sodio", unit: "mg/L Na⁺" },
  { key: "potasio", label: "Potasio", unit: "mg/L K⁺" },
  { key: "bicarbonatos", label: "Bicarbonatos", unit: "mg/L HCO₃⁻" },
];

export function classifyIrca(value) {
  if (value > 80) return ircaLegend[0];
  if (value > 35) return ircaLegend[1];
  if (value > 14) return ircaLegend[2];
  if (value > 5) return ircaLegend[3];
  return ircaLegend[4];
}

export function formatValue(value) {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "number") {
    if (Number.isInteger(value)) return value.toString();
    return value.toFixed(2).replace(/\.00$/, "");
  }
  return value;
}
